name: Build, Test, and Update GitHub Project

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  docker-compose-test:
    name: Test Docker Compose Services and Update GitHub Project
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose jq

      - name: Build and start Docker Compose services
        run: |
          docker-compose up --build -d
          docker ps

      - name: Test Flask service
        run: |
          for i in {1..10}; do
            curl -f http://localhost:5000 && break || sleep 5
          done

      - name: Test JupyterLab service
        run: |
          for i in {1..10}; do
            curl -f http://localhost:8888 && break || sleep 5
          done

      - name: Test PostgreSQL service
        run: |
          for i in {1..10}; do
            docker exec postgres_service pg_isready -U user && break || sleep 5
          done

      - name: Test Prophet service
        run: |
          for i in {1..10}; do
            docker exec prophet_service python -m prophet.main && break || sleep 5
          done

      - name: Display Docker Compose logs
        if: failure()
        run: docker-compose logs

      - name: Tear down services
        if: always()
        run: docker-compose down

      - name: Create GitHub Project
        env:
          GH_TOKEN: ${{ secrets.PAT }}
        run: |
          gh project create \
            --title "Prophet Time Series: v0.0.1" \
            --owner Themis128

      - name: Add Description to GitHub Project
        env:
          GH_TOKEN: ${{ secrets.PAT }}
        run: |
          PROJECT_ID=$(gh project list --owner Themis128 --format json | jq -r '.[] | select(.name == "Prophet Time Series: v0.0.1") | .id')
          gh project edit $PROJECT_ID --body "This project is for managing the Prophet Time Series application for version v0.0.1."
