name: Build and Test with Docker Compose

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  docker-compose-test:
    name: Test Docker Compose Services
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Docker
      uses: docker/setup-buildx-action@v2

    - name: Build and start Docker Compose services
      run: |
        docker-compose up --build -d
        docker ps

    - name: Wait for Flask service to be ready
      run: |
        for i in {1..10}; do
          curl -f http://localhost:5000 && break || sleep 5
        done || exit 1

    - name: Test JupyterLab
      run: curl -f http://localhost:8888 || exit 1

    - name: Test PostgreSQL database
      run: |
        docker exec postgres_service psql -U user -d prophet_db -c "\l"

    - name: Tear down services
      if: always()
      run: docker-compose down

  build-and-test-python:
    name: Build and Test Python
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        python-version: ["3.10"]
        os: ["macos-13", "ubuntu-latest", "windows-latest", "macos-latest-xlarge"]
      fail-fast: false

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
        cache: pip

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run tests
      run: python -m pytest prophet/tests/
